<a href="https://colab.research.google.com/github/MeSoumilHu/Pytorch/blob/main/gettingStartedWithPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hellow world")


hellow world


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


In [ ]:
!nvidia-smi


In [3]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3 ],[4,12,10]],[[14,13,17],[34,19,52]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4, 12, 10]],

        [[14, 13, 17],
         [34, 19, 52]]])

In [4]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4, 12, 10]])

In [5]:
TENSOR.ndim

3

In [7]:
TENSOR.shape

torch.Size([2, 2, 3])

In [11]:
#random tensor
random_tensor=torch.rand(1,5,5)
random_tensor,random_tensor.ndim

(tensor([[[0.0736, 0.1908, 0.6751, 0.3455, 0.8345],
          [0.2616, 0.9141, 0.2641, 0.4656, 0.1545],
          [0.5848, 0.7276, 0.1378, 0.2934, 0.3072],
          [0.3158, 0.7663, 0.4755, 0.8176, 0.6988],
          [0.8820, 0.2910, 0.7325, 0.9030, 0.8316]]]),
 3)

In [16]:
zero=torch.zeros(1,5,5)
zero

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [17]:
zero*random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [18]:
one=torch.ones(1,5,5)
one,one.dtype

(tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]),
 torch.float32)

In [23]:
#torch.arange
one_to_ten=torch.arange(1,1000,100)
one_to_ten

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [24]:
#_like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
#data types
float_32_tensor=torch.rand(1,5,5)
float_32_tensor

tensor([[[0.3172, 0.0209, 0.3426, 0.4342, 0.8021],
         [0.3392, 0.7644, 0.7191, 0.7332, 0.6071],
         [0.7424, 0.6007, 0.7766, 0.7068, 0.1909],
         [0.6409, 0.8015, 0.8402, 0.9895, 0.7684],
         [0.6619, 0.5434, 0.8612, 0.6162, 0.9024]]])

In [27]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16